name: "Append Github PR description"
description: "Append the provided URL to Github pull request description"
branding:
  icon: "align-left"
  color: "blue"
inputs:
  auth:
    description: "The github auth token"
    required: true
  repo:
    description: "The github repo name"
    required: true
  owner:
    description: "The github repo owner"
    required: true
  pr:
    description: "The pr number"
    required: true
  url:
    description: "The output url"
    required: true
  message:
    description: "The output message (optional)"
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
